name = "42nd SOC Development Mod";
picture = "\x\55th_dev\addons\55th_arsenals\55th_SOR_Icon_1.paa";
logo = "\x\55th_dev\addons\55th_arsenals\55th_SOR_Icon_1.paa";
logoOver = "\x\55th_dev\addons\55th_arsenals\55th_SOR_Icon_1.paa";
logoSmall = "\x\55th_dev\addons\55th_arsenals\55th_SOR_Icon_1.paa";
description = "42nd SOC Development Mod";
author = "42nd SOC";
actionName = "Website";
action = "https://github.com/sgtobliterator/55th-SOR-Development-Mods";
