class CfgPatches
{
	class 3den_Objects
	{
		units[]=
		{
			"Bandage_Roll_F",
			"Banner_AAF_F",
			"Banner_CSAT_F",
			"Banner_FIA_F",
			"Banner_TFA_F",
			"Bed_Old_F",
			"Blue_Shield_F",
			"Blue_Shield_English_F",
			"Blue_Shield_French_F",
			"Blue_Shield_Greek_F",
			"Bunk_Beds_F",
			"Bunk_Beds_CTRG_F",
			"Bunk_Beds_CSAT_F",
			"Cabinet_NATO_F",
			"Cabinet_CSAT_F",
			"Chemlights_Box_F",
			"Clipboard_F",
			"Combat_Knife_F",
			"Counter_F",
			"Eau_de_Combat_F",
			"Eau_de_Combat_Box_F",
			"Exhibition_Stand_F",
			"Flashdrive_F",
			"IDAP_Mug_F",
			"IDAP_Road_Sign_F",
			"IDAP_Sign_F",
			"KA60_Wreck_F",
			"KA60_Wreck_Door_F",
			"KA60_Wreck_Rotor_F",
			"KA60_Wreck_Tail_F",
			"Mattress_Old_F",
			"Metal_Locker_F",
			"Microphone_F",
			"Narcotics_F",
			"Narcotics_Three_F",
			"Newspaper_F",
			"Paperback_F",
			"Picture_Frame_Landscape_F",
			"Picture_Frame_Portrait_F",
			"Portable_GCS_Hub_F",
			"Portable_GCS_Hub_CTRG_F",
			"Portable_GCS_Packed_F",
			"Portable_GCS_CTRG_Packed_F",
			"Portable_GCS_F",
			"Sign_Hotel_F",
			"Tactical_Screen_F",
			"Tactical_Screen_On_F",
			"V_Press_AAN_F"
		};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]={};
	};
};
class CfgMods
{
	class Mod_Base;
	class 3den_objects_Mod: Mod_Base
	{
		picture="\3den_objects\icons_f\3den_objects_icon_ca.paa";
		logo="\3den_objects\icons_f\3den_objects_logo_ca.paa";
		logoSmall="\3den_objects\icons_f\3den_objects_logo_Small_ca.paa";
		logoOver="\3den_objects\icons_f\3den_objects_logo_hover_ca.paa";
		tooltipOwned="Eden Objects";
		action="https://forums.bistudio.com/topic/188723-eden-objects/";
		dlcColor[]={0.31,0.77999997,0.77999997,1};
		overview="A selection of objects created to celebrate the launch of the Eden editor.";
		hideName=1;
		hidePicture=0;
		name="Eden Objects";
		dir="3den_Objects";
	};
	author="Kydoimos";
	timepacked="1511952226";
};
class CfgAnimationSourceSounds
{
	class Locker
	{
		class OpenTheDoor
		{
			loop=0;
			terminate=0;
			trigger="direction * (phase factor[0.01,0.02])";
			sound0[]=
			{
				"3den_objects\sounds_f\locker_door_open.wss",
				1,
				1,
				100
			};
			sound[]=
			{
				"sound0",
				1
			};
		};
		class SlamTheDoor
		{
			loop=0;
			terminate=0;
			trigger="(1 - direction) * (phase factor[0.98,0.99])";
			sound0[]=
			{
				"3den_objects\sounds_f\locker_door_close.wss",
				1,
				1,
				100
			};
			sound[]=
			{
				"sound0",
				1
			};
		};
	};
};
class CfgMovesBasic
{
	class DefaultDie;
	class ManActions
	{
		UAV_Pilot="UAV_Pilot";
		UAV_Pilot_KIA="UAV_Pilot_KIA";
	};
};
class CfgMovesMaleSdr: CfgMovesBasic
{
	class States
	{
		class Crew;
		class cutSceneAnimationBase;
		class crew_tank01_in;
		class UAV_Pilot: crew_tank01_in
		{
			file="\3den_objects\anims_f\uav_Pilot";
			head="default";
			interpolateTo[]=
			{
				"UAV_Pilot_KIA",
				1
			};
		};
		class UAV_Pilot_Idle: crew_tank01_in
		{
			file="\3den_objects\anims_f\uav_pilot_idle";
			head="default";
			looped=1;
			speed=0.088799901;
			interpolateTo[]=
			{
				"UAV_Pilot_KIA",
				1
			};
		};
		class UAV_Pilot_KIA: DefaultDie
		{
			actions="DeadActions";
			file="\3den_objects\anims_f\uav_pilot_kia";
			head="headNo";
			looped=0;
			speed=0.31879991;
			connectTo[]=
			{
				"Unconscious",
				0.1
			};
			soundEnabled=0;
			interpolateTo[]={};
			terminal=1;
			interpolationRestart=0;
		};
		class Dead_Pilot: cutSceneAnimationBase
		{
			file="\3den_objects\anims_f\dead_pilot";
			head="headNo";
			looped=1;
			speed=0.0072880001;
			connectTo[]={};
			interpolateTo[]={};
			terminal=1;
			interpolationRestart=1;
		};
		class Reporter: cutSceneAnimationBase
		{
			file="\3den_objects\anims_f\reporter";
			head="headNo";
			looped=1;
			speed=0.0072880001;
			connectTo[]={};
			interpolateTo[]={};
			terminal=1;
			interpolationRestart=1;
		};
		class Unarmed_Reading_Clipboard: cutSceneAnimationBase
		{
			file="\3den_objects\anims_f\unarmed_reading_clipboard";
			head="headNo";
			looped=1;
			speed=0.068799898;
			connectTo[]={};
			interpolateTo[]={};
			interpolationRestart=1;
		};
		class UAV_Observer: cutSceneAnimationBase
		{
			file="\3den_objects\anims_f\uav_observer";
			head="default";
			looped=1;
			speed=0.0072880001;
			connectTo[]={};
			interpolateTo[]={};
			terminal=1;
			interpolationRestart=0;
		};
		class UAV_Observer_Idle: UAV_Observer
		{
			file="\3den_objects\anims_f\uav_observer_idle";
			head="default";
			looped=0;
			speed=0.1487999;
			connectTo[]=
			{
				"UAV_observer",
				0.0099999998
			};
			interpolateFrom[]=
			{
				"UAV_observer",
				1
			};
			interpolateTo[]=
			{
				"UAV_observer",
				1
			};
		};
	};
};
class cfgVehicles
{
	class B_Soldier_Base_F;
	class House;
	class Items_base_F;
	class Land_Wreck_Heli_Attack_01_F;
	class Static;
	class Bandage_Roll_F: Items_base_F
	{
		author="Kydoimos";
		editorPreview="3den_Objects\data_f\editor_previews_f\bandage_roll_f.jpg";
		dlc="3den_objects_mod";
		editorCategory="EdCat_Things";
		editorSubcategory="EdSubcat_Medicine";
		displayName="$STR_Bandage_Roll_F";
		icon="iconObject_1x3";
		scope=2;
		scopeCurator=2;
		_generalMacro="Bandage_Roll_F";
		model="\3den_objects\objects_f\bandage_roll_f\bandage_roll_f.p3d";
		vehicleClass="small_items";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsMaterials[]=
		{
			"\3den_objects\characters_f\heads\common\data\h_bandage_head.rvmat"
		};
		hiddenSelectionsTextures[]=
		{
			"\3den_objects\characters_f\heads\common\data\h_bandage_head_co.paa"
		};
	};
	class Banner_AAF_F: Static
	{
		author="Kydoimos";
		editorPreview="3den_objects\data_f\editor_previews_f\banner_aaf_f.jpg";
		dlc="3den_objects_mod";
		editorCategory="EdCat_Signs";
		editorSubcategory="EdSubcat_Military";
		displayName="$STR_Banner_AAF_F";
		icon="iconObject_5x1";
		scope=2;
		scopeCurator=2;
		_generalMacro="Banner_AAF_F";
		model="\3den_objects\objects_f\banner_f\banner_f.p3d";
		vehicleClass="signs";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsMaterials[]=
		{
			"\3den_objects\objects_f\banner_f\banner.rvmat"
		};
		hiddenSelectionsTextures[]=
		{
			"\3den_objects\objects_f\banner_f\faction_banners\banner_aaf_co.paa"
		};
	};
	class Banner_CSAT_F: Banner_AAF_F
	{
		editorPreview="3den_objects\data_f\editor_previews_f\banner_csat_f.jpg";
		dlc="3den_objects_mod";
		displayName="$STR_Banner_CSAT_F";
		_generalMacro="Banner_CSAT_F";
		hiddenSelectionsTextures[]=
		{
			"\3den_objects\objects_f\banner_f\faction_banners\banner_csat_co.paa"
		};
	};
	class Banner_FIA_F: Banner_CSAT_F
	{
		editorPreview="3den_objects\data_f\editor_previews_f\banner_fia_f.jpg";
		dlc="3den_objects_mod";
		displayName="$STR_Banner_FIA_F";
		_generalMacro="Banner_FIA_F";
		hiddenSelectionsTextures[]=
		{
			"\3den_objects\objects_f\banner_f\faction_banners\banner_fia_co.paa"
		};
	};
	class Banner_TFA_F: Banner_FIA_F
	{
		editorPreview="3den_objects\data_f\editor_previews_f\banner_tfa_f.jpg";
		dlc="3den_objects_mod";
		displayName="$STR_Banner_TFA_F";
		_generalMacro="Banner_TFA_F";
		hiddenSelectionsTextures[]=
		{
			"\3den_objects\objects_f\banner_f\faction_banners\banner_TFA_co.paa"
		};
	};
	class Bed_Old_F: Items_base_F
	{
		author="Kydoimos";
		editorPreview="3den_objects\data_f\editor_previews_f\bed_old_f.jpg";
		dlc="3den_objects_mod";
		editorCategory="EdCat_Furniture";
		editorSubcategory="EdSubcat_Garbage";
		displayName="$STR_Bed_Old_F";
		icon="iconObject_1x2";
		mapSize=2;
		scope=2;
		scopeCurator=2;
		_generalMacro="Bed_Old_F";
		model="\3den_objects\objects_f\bed_old_f\bed_old_f.p3d";
		vehicleClass="small_items";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsMaterials[]=
		{
			"\3den_objects\objects_f\bed_old_f\bed_old.rvmat"
		};
		hiddenSelectionsTextures[]=
		{
			"\3den_objects\objects_f\bed_old_f\bed_old_co.paa"
		};
	};
	class Blue_Shield_F: Static
	{
		author="Kydoimos";
		editorPreview="3den_objects\data_f\editor_previews_f\blue_shield_f.jpg";
		dlc="3den_objects_mod";
		editorCategory="EdCat_Signs";
		editorSubcategory="EdSubcat_WarningSigns";
		displayName="$STR_Blue_Shield_F";
		icon="iconObject_1x1";
		scope=2;
		scopeCurator=2;
		_generalMacro="Blue_Shield_F";
		model="\3den_Objects\Objects_F\Blue_Shield_F\Blue_Shield_F.p3d";
		vehicleClass="signs";
	};
	class Blue_Shield_English_F: Blue_Shield_F
	{
		editorPreview="3den_objects\data_f\editor_previews_f\blue_shield_english_f.jpg";
		displayName="$STR_Blue_Shield_English_F";
		_generalMacro="Blue_Shield_English_F";
		model="\3den_Objects\Objects_F\Blue_Shield_F\Blue_Shield_English_F.p3d";
	};
	class Blue_Shield_French_F: Blue_Shield_F
	{
		editorPreview="3den_objects\data_f\editor_previews_f\blue_shield_french_f.jpg";
		displayName="$STR_Blue_Shield_French_F";
		_generalMacro="Blue_Shield_French_F";
		model="\3den_Objects\Objects_F\Blue_Shield_F\Blue_Shield_French_F.p3d";
	};
	class Blue_Shield_Greek_F: Blue_Shield_F
	{
		editorPreview="3den_objects\data_f\editor_previews_f\blue_shield_greek_f.jpg";
		displayName="$STR_Blue_Shield_Greek_F";
		_generalMacro="Blue_Shield_Greek_F";
		model="\3den_Objects\Objects_F\Blue_Shield_F\Blue_Shield_Greek_F.p3d";
	};
	class Bunk_Beds_F: Items_base_F
	{
		author="Kydoimos";
		editorPreview="3den_objects\data_f\editor_previews_f\bunk_beds_f.jpg";
		dlc="3den_objects_mod";
		editorCategory="EdCat_Furniture";
		editorSubcategory="EdSubcat_Military";
		displayName="$STR_Bunk_Beds_F";
		icon="iconObject_1x2";
		mapSize=2;
		scope=2;
		scopeCurator=2;
		_generalMacro="Bunk_Beds_F";
		model="\3den_objects\objects_f\bunk_beds_f\bunk_beds_f.p3d";
		vehicleClass="small_items";
		hiddenSelections[]=
		{
			"camo1",
			"camo2"
		};
		hiddenSelectionsMaterials[]=
		{
			"\3den_objects\objects_f\bunk_beds_f\bunk_beds.rvmat",
			"\3den_objects\objects_f\bunk_beds_f\bunk_beds_frame.rvmat"
		};
		hiddenSelectionsTextures[]=
		{
			"\3den_objects\objects_f\bunk_beds_f\bunk_beds_co.paa",
			"\3den_objects\objects_f\bunk_beds_f\bunk_beds_co.paa"
		};
	};
	class Bunk_Beds_CTRG_F: Bunk_Beds_F
	{
		editorPreview="3den_objects\data_f\editor_previews_f\bunk_beds_ctrg_f.jpg";
		dlc="3den_objects_mod";
		displayName="$STR_Bunk_Beds_CTRG_F";
		_generalMacro="Bunk_Beds_CTRG_F";
		hiddenSelections[]=
		{
			"camo1",
			"camo2"
		};
		hiddenSelectionsMaterials[]=
		{
			"\3den_objects\objects_f\bunk_beds_f\bunk_beds.rvmat",
			"\3den_objects\objects_f\bunk_beds_f\bunk_beds_frame.rvmat"
		};
		hiddenSelectionsTextures[]=
		{
			"\3den_objects\objects_f\bunk_beds_f\bunk_beds_CTRG_co.paa",
			"\3den_objects\objects_f\bunk_beds_f\bunk_beds_CTRG_co.paa"
		};
	};
	class Bunk_Beds_CSAT_F: Bunk_Beds_CTRG_F
	{
		editorPreview="3den_objects\data_f\editor_previews_f\bunk_beds_csat_f.jpg";
		dlc="3den_objects_mod";
		displayName="$STR_Bunk_Beds_CSAT_F";
		_generalMacro="Bunk_Beds_CSAT_F";
		hiddenSelections[]=
		{
			"camo1",
			"camo2"
		};
		hiddenSelectionsMaterials[]=
		{
			"\3den_objects\objects_f\bunk_beds_f\bunk_beds.rvmat",
			"\3den_objects\objects_f\bunk_beds_f\bunk_beds_frame.rvmat"
		};
		hiddenSelectionsTextures[]=
		{
			"\3den_objects\objects_f\bunk_beds_f\bunk_beds_CSAT_co.paa",
			"\3den_objects\objects_f\bunk_beds_f\bunk_beds_CSAT_co.paa"
		};
	};
	class Cabinet_NATO_F: Items_base_F
	{
		author="Kydoimos";
		editorPreview="3den_objects\data_f\editor_previews_f\cabinet_nato_f.jpg";
		dlc="3den_objects_mod";
		editorCategory="EdCat_Furniture";
		editorSubcategory="EdSubcat_Military";
		scope=2;
		scopeCurator=2;
		icon="iconObject_1x2";
		model="\3den_objects\objects_f\cabinet_f\cabinet_f.p3d";
		displayName="$STR_Cabinet_NATO_F";
		_generalMacro="Cabinet_NATO_F";
		vehicleClass="small_items";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsMaterials[]=
		{
			"\3den_objects\objects_f\cabinet_f\cabinet.rvmat"
		};
		hiddenSelectionsTextures[]=
		{
			"\3den_objects\objects_f\cabinet_f\cabinet_co.paa"
		};
		maximumLoad=100;
		transportMaxMagazines=10;
		class EventHandlers
		{
			ContainerOpened="_cabinet_opened = (_this select 0); if ((_cabinet_opened animationPhase 'Cabinet_Rotation') < 0.5) then {_cabinet_opened animate [""Cabinet_Rotation"", 1]}";
			ContainerClosed="_cabinet_closed = (_this select 0); if ((_cabinet_closed animationPhase 'Cabinet_Rotation') >= 0.5) then {_cabinet_closed animate [""Cabinet_Rotation"", 0]}";
		};
		class AnimationSources
		{
			class Cabinet_Rotation
			{
				source="user";
				initPhase=0;
				animPeriod=1.45;
				Sound="Locker";
				SoundPosition="ActionPoint";
			};
		};
	};
	class Cabinet_CSAT_F: Cabinet_NATO_F
	{
		editorPreview="3den_objects\data_f\editor_previews_f\cabinet_csat_f.jpg";
		displayName="$STR_Cabinet_CSAT_F";
		_generalMacro="Cabinet_CSAT_F";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsMaterials[]=
		{
			"\3den_objects\objects_f\cabinet_f\cabinet.rvmat"
		};
		hiddenSelectionsTextures[]=
		{
			"\3den_objects\objects_f\cabinet_f\cabinet_hex_co.paa"
		};
	};
	class Chemlight_Box_F: Items_base_F
	{
		author="Kydoimos";
		editorPreview="3den_objects\data_f\editor_previews_f\chemlight_box_f.jpg";
		dlc="3den_objects_mod";
		editorCategory="EdCat_Things";
		editorSubcategory="EdSubcat_Military";
		scope=2;
		scopeCurator=2;
		icon="iconObject_1x2";
		model="\3den_objects\objects_f\chemlight_box_f\chemlight_box_f.p3d";
		displayName="$STR_Chemlight_Box_F";
		_generalMacro="Chemlight_Box_F";
		vehicleClass="small_items";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsMaterials[]=
		{
			"\3den_objects\objects_f\chemlight_box_f\chemlight_box.rvmat"
		};
		hiddenSelectionsTextures[]=
		{
			"\3den_objects\objects_f\chemlight_box_f\chemlight_box_co.paa"
		};
		maximumLoad=12;
		transportMaxMagazines=12;
		class EventHandlers
		{
			init="(_this select 0) addMagazineCargoGlobal ['Chemlight_Green', 3]; (_this select 0) addMagazineCargoGlobal ['Chemlight_Red', 3]; (_this select 0) addMagazineCargoGlobal ['Chemlight_Yellow', 3]; (_this select 0) addMagazineCargoGlobal ['Chemlight_Blue', 3];";
		};
	};
	class Clipboard_F: Items_base_F
	{
		author="Kydoimos";
		editorPreview="3den_objects\data_f\editor_previews_f\clipboard_f.jpg";
		dlc="3den_objects_mod";
		editorCategory="EdCat_Things";
		editorSubcategory="EdSubcat_Intel";
		displayName="$STR_Clipboard_F";
		icon="iconObject_1x1";
		scope=2;
		scopeCurator=2;
		_generalMacro="Clipboard_F";
		model="\3den_objects\objects_f\clipboard_f\clipboard_f.p3d";
		vehicleClass="small_items";
	};
	class Combat_Knife_F: Items_base_F
	{
		author="Kydoimos";
		editorPreview="3den_objects\data_f\editor_previews_f\combat_knife_f.jpg";
		dlc="3den_objects_mod";
		editorCategory="EdCat_Things";
		editorSubcategory="EdSubcat_Military";
		displayName="$STR_Combat_Knife_F";
		icon="iconObject_1x3";
		scope=2;
		scopeCurator=2;
		_generalMacro="Combat_Knife_F";
		model="\3den_objects\objects_f\combat_knife_f\combat_knife_f.p3d";
		vehicleClass="military";
	};
	class Counter_F: Items_base_F
	{
		author="Kydoimos";
		editorPreview="3den_objects\data_f\editor_previews_f\counter_f.jpg";
		dlc="3den_objects_mod";
		editorCategory="EdCat_Furniture";
		editorSubcategory="EdSubcat_Shops";
		displayName="$STR_Counter_F";
		icon="iconObject_1x2";
		mapSize=2;
		scope=2;
		scopeCurator=2;
		_generalMacro="Counter_F";
		model="\3den_objects\objects_f\counter_f\counter_f.p3d";
		vehicleClass="small_items";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsMaterials[]=
		{
			"\3den_objects\objects_f\counter_f\counter.rvmat"
		};
		hiddenSelectionsTextures[]=
		{
			"\3den_objects\objects_f\counter_f\counter_co.paa"
		};
	};
	class Eau_de_Combat_F: Items_base_F
	{
		author="Kydoimos";
		editorPreview="3den_objects\data_f\editor_previews_f\eau_de_combat_f.jpg";
		dlc="3den_objects_mod";
		_generalMacro="Eau_de_Combat_F";
		scope=2;
		scopeCurator=2;
		icon="iconObject_1x1";
		model="\3den_objects\objects_f\eau_de_combat_f\eau_de_combat_f.p3d";
		displayName="$STR_Eau_de_Combat_F";
		vehicleClass="small_items";
		editorCategory="EdCat_Things";
		editorSubcategory="EdSubcat_Sports";
	};
	class Eau_de_Combat_Box_F: Items_base_F
	{
		author="Kydoimos";
		editorPreview="3den_objects\data_f\editor_previews_f\eau_de_combat_box_f.jpg";
		dlc="3den_objects_mod";
		_generalMacro="Eau_de_Combat_Box_F";
		scope=2;
		scopeCurator=2;
		icon="iconObject_1x1";
		model="\3den_objects\objects_f\eau_de_combat_box_f\eau_de_combat_box_f.p3d";
		displayName="$STR_Eau_de_Combat_Box_F";
		vehicleClass="small_items";
		editorCategory="EdCat_Things";
		editorSubcategory="EdSubcat_Sports";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsMaterials[]=
		{
			"\3den_objects\objects_f\eau_de_combat_box_f\eau_de_combat_box.rvmat"
		};
		hiddenSelectionsTextures[]=
		{
			"\3den_objects\objects_f\eau_de_combat_box_f\eau_de_combat_box_co.paa"
		};
	};
	class Exhibition_Stand_F: Items_base_F
	{
		author="Kydoimos";
		editorPreview="3den_objects\data_f\editor_previews_f\exhibition_stand_f.jpg";
		dlc="3den_objects_mod";
		editorCategory="EdCat_Signs";
		editorSubcategory="EdSubcat_Blanksigns";
		displayName="$STR_Exhibition_Stand_F";
		icon="iconObject_5x1";
		scope=2;
		scopeCurator=2;
		_generalMacro="Exhibition_Stand_F";
		model="\3den_Objects\Objects_F\Exhibition_Stand_F\Exhibition_Stand_F.p3d";
		vehicleClass="signs";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3"
		};
		hiddenSelectionsMaterials[]=
		{
			"\3den_Objects\Objects_F\Exhibition_Stand_F\Data\Exhibition_Stand_Soft.rvmat",
			"\3den_Objects\Objects_F\Exhibition_Stand_F\Data\Exhibition_Stand_Soft.rvmat",
			"\3den_Objects\Objects_F\Exhibition_Stand_F\Data\Exhibition_Stand_Soft.rvmat"
		};
		hiddenSelectionsTextures[]=
		{
			"\3den_Objects\Objects_F\Exhibition_Stand_F\Data\Exhibition_Stand_Board_co.paa",
			"\3den_Objects\Objects_F\Exhibition_Stand_F\Data\Exhibition_Stand_Board_co.paa",
			"\3den_Objects\Objects_F\Exhibition_Stand_F\Data\Exhibition_Stand_Board_co.paa"
		};
	};
	class Flashdrive_F: Items_base_F
	{
		author="Kydoimos";
		editorPreview="3den_objects\data_f\editor_previews_f\flashdrive_f.jpg";
		dlc="3den_objects_mod";
		editorCategory="EdCat_Things";
		editorSubcategory="EdSubcat_Electronics";
		displayName="$STR_Flashdrive_F";
		icon="iconObject_1x3";
		scope=2;
		scopeCurator=2;
		_generalMacro="Flashdrive_F";
		model="\3den_objects\objects_f\flashdrive_f\flashdrive_f.p3d";
		vehicleClass="small_items";
	};
	class IDAP_Mug_F: Items_base_F
	{
		author="Kydoimos";
		editorPreview="3den_objects\data_f\editor_previews_f\idap_mug_f.jpg";
		dlc="3den_objects_mod";
		editorCategory="EdCat_Things";
		editorSubcategory="EdSubcat_Office";
		displayName="$STR_IDAP_Mug_F";
		icon="iconObject_1x1";
		scope=2;
		scopeCurator=2;
		_generalMacro="IDAP_Mug_F";
		model="\3den_Objects\Objects_F\IDAP_Mug_F\IDAP_Mug_F.p3d";
		vehicleClass="small_items";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsMaterials[]=
		{
			"\3den_Objects\Objects_F\IDAP_Mug_F\Data\IDAP_Mug.rvmat"
		};
		hiddenSelectionsTextures[]=
		{
			"\3den_Objects\Objects_F\IDAP_Mug_F\Data\IDAP_Mug_co.paa"
		};
	};
	class IDAP_Sign_F: Static
	{
		author="Kydoimos";
		editorPreview="3den_objects\data_f\editor_previews_f\idap_sign_f.jpg";
		dlc="3den_objects_mod";
		editorCategory="EdCat_Signs";
		editorSubcategory="EdSubcat_WarningSigns";
		displayName="$STR_IDAP_Road_Sign_F";
		icon="iconObject_5x1";
		scope=2;
		scopeCurator=2;
		_generalMacro="IDAP_Sign_F";
		model="\3den_Objects\Objects_F\IDAP_Sign_F\IDAP_Sign_F.p3d";
		vehicleClass="signs";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsMaterials[]=
		{
			"\3den_Objects\Objects_F\IDAP_Sign_F\Data\IDAP_Sign.rvmat"
		};
		hiddenSelectionsTextures[]=
		{
			"\3den_Objects\Objects_F\IDAP_Sign_F\Data\IDAP_Sign_co.paa"
		};
	};
	class KA60_Wreck_F: Land_Wreck_Heli_Attack_01_F
	{
		author="Kydoimos";
		editorPreview="3den_objects\data_f\editor_previews_f\ka60_wreck_f.jpg";
		dlc="3den_objects_mod";
		scope=2;
		scopeCurator=2;
		model="\3den_objects\objects_f\ka60_wreck_f\ka60_wreck_f.p3d";
		displayName="$STR_KA60_Wreck_F";
		vehicleClass="Wreck";
		editorCategory="EdCat_Wrecks";
		editorSubcategory="EdSubcat_Helicopters";
		hiddenSelections[]=
		{
			"Camo1",
			"Camo2"
		};
		hiddenSelectionsMaterials[]=
		{
			"\3den_objects\objects_f\ka60_wreck_f\aan_ka60_ext.rvmat",
			"\3den_objects\objects_f\ka60_wreck_f\aan_ka60_ext.rvmat"
		};
		hiddenSelectionsTextures[]=
		{
			"\3den_objects\objects_f\ka60_wreck_f\aan_ka60_ext_co.paa",
			"\3den_objects\objects_f\ka60_wreck_f\aan_ka60_ext_co.paa"
		};
		class EventHandlers
		{
			init="(_this select 0) execVM '3den_objects\objects_f\ka60_wreck_f\scripts\ka60_wreckage.sqf'";
		};
	};
	class KA60_Wreck_Door_F: Items_base_F
	{
		author="Kydoimos";
		editorPreview="3den_objects\data_f\editor_previews_f\ka60_wreck_door_f.jpg";
		dlc="3den_objects_mod";
		displayName="$STR_KA60_Wreck_Door_F";
		icon="iconObject_3x2";
		scope=2;
		scopeCurator=2;
		_generalMacro="KA60_Wreck_Door_F";
		model="\3den_objects\objects_f\ka60_wreck_f\ka60_wreck_door_f.p3d";
		vehicleClass="Wreck";
		editorCategory="EdCat_Wrecks";
		editorSubcategory="EdSubcat_Helicopters";
		hiddenSelections[]=
		{
			"Camo1"
		};
		hiddenSelectionsMaterials[]=
		{
			"\3den_objects\objects_f\ka60_wreck_f\aan_ka60_ext.rvmat"
		};
		hiddenSelectionsTextures[]=
		{
			"\3den_objects\objects_f\ka60_wreck_f\aan_ka60_ext_co.paa"
		};
	};
	class KA60_Wreck_Rotor_F: Items_base_F
	{
		author="Kydoimos";
		editorPreview="3den_objects\data_f\editor_previews_f\ka60_wreck_rotor_f.jpg";
		dlc="3den_objects_mod";
		displayName="$STR_KA60_Wreck_Rotor_F";
		icon="iconObject_3x2";
		scope=2;
		scopeCurator=2;
		_generalMacro="KA60_Wreck_Rotor_F";
		model="\3den_objects\objects_f\ka60_wreck_f\ka60_wreck_rotor_f.p3d";
		vehicleClass="Wreck";
		editorCategory="EdCat_Wrecks";
		editorSubcategory="EdSubcat_Helicopters";
	};
	class KA60_Wreck_Tail_F: Static
	{
		author="Kydoimos";
		editorPreview="3den_objects\data_f\editor_previews_f\ka60_wreck_tail_f.jpg";
		dlc="3den_objects_mod";
		displayName="$STR_KA60_Wreck_Tail_F";
		icon="iconObject_3x2";
		scope=2;
		scopeCurator=2;
		_generalMacro="KA60_Wreck_Door_F";
		model="\3den_objects\objects_f\ka60_wreck_f\ka60_wreck_tail_f.p3d";
		vehicleClass="Wreck";
		editorCategory="EdCat_Wrecks";
		editorSubcategory="EdSubcat_Helicopters";
		hiddenSelections[]=
		{
			"Camo1"
		};
		hiddenSelectionsMaterials[]=
		{
			"\3den_objects\objects_f\ka60_wreck_f\aan_ka60_ext.rvmat"
		};
		hiddenSelectionsTextures[]=
		{
			"\3den_objects\objects_f\ka60_wreck_f\aan_ka60_tail_ext_co.paa"
		};
	};
	class Mattress_Old_F: Items_base_F
	{
		author="Kydoimos";
		editorPreview="3den_objects\data_f\editor_previews_f\mattress_old_f.jpg";
		dlc="3den_objects_mod";
		editorCategory="EdCat_Furniture";
		editorSubcategory="EdSubcat_Garbage";
		displayName="$STR_Mattress_Old_F";
		icon="iconObject_1x2";
		mapSize=2;
		scope=2;
		scopeCurator=2;
		_generalMacro="Mattress_Old_F";
		model="\3den_objects\objects_f\mattress_old_f\mattress_old_f.p3d";
		vehicleClass="furniture";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsMaterials[]=
		{
			"\3den_objects\objects_f\bed_old_f\bed_old.rvmat"
		};
		hiddenSelectionsTextures[]=
		{
			"\3den_objects\objects_f\bed_old_f\bed_old_co.paa"
		};
	};
	class Metal_Locker_F: Items_base_F
	{
		author="Kydoimos";
		editorPreview="3den_objects\data_f\editor_previews_f\metal_locker_f.jpg";
		dlc="3den_objects_mod";
		editorCategory="EdCat_Furniture";
		editorSubcategory="EdSubcat_Military";
		scope=2;
		scopeCurator=2;
		icon="iconObject_1x2";
		model="\3den_objects\objects_f\metal_locker_f\metal_locker_f.p3d";
		displayName="$STR_Metal_Locker_F";
		vehicleClass="small_items";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsMaterials[]=
		{
			"\3den_objects\objects_f\metal_locker_f\metal_locker_pictures.rvmat"
		};
		hiddenSelectionsTextures[]=
		{
			"\3den_objects\objects_f\metal_locker_f\metal_locker_pictures_co.paa"
		};
		maximumLoad=500;
		transportMaxMagazines=10;
		class EventHandlers
		{
			ContainerOpened="_locker_opened = (_this select 0); if ((_locker_opened animationPhase 'Metal_Locker_Rotation') < 0.5) then {_locker_opened animate [""Metal_Locker_Rotation"", 1]}";
			ContainerClosed="_locker_closed = (_this select 0); if ((_locker_closed animationPhase 'Metal_Locker_Rotation') >= 0.5) then {_locker_closed animate [""Metal_Locker_Rotation"", 0]}";
		};
		class AnimationSources
		{
			class Metal_Locker_Rotation
			{
				source="user";
				initPhase=0;
				animPeriod=1.45;
				Sound="Locker";
				SoundPosition="ActionPoint";
			};
		};
		class UserActions
		{
			class openLocker
			{
				priority=6;
				displayName="Open";
				position="ActionPoint";
				radius=4;
				onlyForPlayer=0;
				showWindow=0;
				condition="((this animationPhase 'Metal_Locker_Rotation') < 0.5)";
				statement="this animate [""Metal_Locker_Rotation"", 1]";
			};
			class closeLocker
			{
				priority=6;
				displayName="Close";
				position="ActionPoint";
				radius=4;
				onlyForPlayer=0;
				showWindow=0;
				condition="((this animationPhase 'Metal_Locker_Rotation') >= 0.5)";
				statement="this animate [""Metal_Locker_Rotation"", 0]";
			};
		};
	};
	class Microphone_F: Items_base_F
	{
		author="Kydoimos";
		editorPreview="3den_objects\data_f\editor_previews_f\microphone_f.jpg";
		dlc="3den_objects_mod";
		displayName="$STR_Microphone_F";
		icon="iconObject_1x1";
		scope=2;
		scopeCurator=2;
		_generalMacro="Microphone_F";
		model="\3den_objects\objects_f\microphone_f\microphone_f.p3d";
		vehicleClass="small_items";
		editorCategory="EdCat_Things";
		editorSubcategory="EdSubcat_Electronics";
	};
	class Narcotics_F: Items_base_F
	{
		author="Kydoimos";
		editorPreview="3den_objects\data_f\editor_previews_f\Narcotics_f.jpg";
		dlc="3den_objects_mod";
		editorCategory="EdCat_Things";
		editorSubcategory="EdSubcat_Intel";
		displayName="$STR_Narcotics_F";
		icon="iconObject_1x1";
		scope=2;
		scopeCurator=2;
		_generalMacro="Narcotics_F";
		model="\3den_objects\objects_f\narcotics_f\narcotics_f.p3d";
		vehicleClass="small_items";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsMaterials[]=
		{
			"\3den_objects\objects_f\narcotics_f\narcotics.rvmat"
		};
		hiddenSelectionsTextures[]=
		{
			"\3den_objects\objects_f\narcotics_f\narcotics_co.paa"
		};
	};
	class Narcotics_Three_F: Items_base_F
	{
		author="Kydoimos";
		editorPreview="3den_objects\data_f\editor_previews_f\narcotics_three_f.jpg";
		dlc="3den_objects_mod";
		editorCategory="EdCat_Things";
		editorSubcategory="EdSubcat_Intel";
		displayName="$STR_Narcotics_Three_F";
		icon="iconObject_1x1";
		scope=2;
		scopeCurator=2;
		_generalMacro="Narcotics_Three_F";
		model="\3den_objects\objects_f\narcotics_f\narcotics_three_f.p3d";
		vehicleClass="small_items";
	};
	class Newspaper_F: Items_base_F
	{
		author="Kydoimos";
		editorPreview="3den_objects\data_f\editor_previews_f\newspaper_f.jpg";
		dlc="3den_objects_mod";
		editorCategory="EdCat_Things";
		editorSubcategory="EdSubcat_Office";
		displayName="$STR_Newspaper_F";
		icon="iconObject_1x1";
		scope=2;
		scopeCurator=2;
		_generalMacro="Newspaper_F";
		model="\3den_Objects\Objects_F\Newspaper_F\Newspaper_F.p3d";
		vehicleClass="small_items";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsMaterials[]=
		{
			"\3den_Objects\Objects_F\Newspaper_F\Data\Newspaper.rvmat"
		};
		hiddenSelectionsTextures[]=
		{
			"\3den_Objects\Objects_F\Newspaper_F\Data\Newspaper_co.paa"
		};
	};
	class Paperback_F: Items_base_F
	{
		author="Kydoimos";
		editorPreview="3den_objects\data_f\editor_previews_f\paperback_f.jpg";
		dlc="3den_objects_mod";
		editorCategory="EdCat_Things";
		editorSubcategory="EdSubcat_Market";
		displayName="$STR_Paperback_F";
		icon="iconObject_1x1";
		scope=2;
		scopeCurator=2;
		_generalMacro="Paperback_F";
		model="\3den_objects\objects_f\paperback_f\paperback_f.p3d";
		vehicleClass="small_items";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsMaterials[]=
		{
			"\3den_objects\objects_f\paperback_f\paperback.rvmat"
		};
		hiddenSelectionsTextures[]=
		{
			"\3den_objects\objects_f\paperback_f\paperback_co.paa"
		};
	};
	class Picture_Frame_Landscape_Base_F: Static
	{
		class HitPoints
		{
			class Picture_Frame_Landscape_Damage;
		};
	};
	class Picture_Frame_Landscape_F: Picture_Frame_Landscape_Base_F
	{
		author="Kydoimos";
		editorPreview="3den_objects\data_f\editor_previews_f\picture_frame_landscape_f.jpg";
		dlc="3den_objects_mod";
		editorCategory="EdCat_Signs";
		editorSubcategory="EdSubcat_Office";
		displayName="$STR_Picture_Frame_F";
		icon="iconObject_5x1";
		scope=2;
		scopeCurator=2;
		_generalMacro="Picture_Frame_landscape_F";
		model="\3den_objects\objects_f\picture_frame_f\picture_frame_f.p3d";
		vehicleClass="signs";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsMaterials[]=
		{
			"\3den_objects\objects_f\picture_frame_f\picture.rvmat"
		};
		hiddenSelectionsTextures[]=
		{
			"\3den_objects\objects_f\picture_frame_f\picture_co.paa"
		};
		class HitPoints: HitPoints
		{
			class Picture_Frame_Landscape_Damage: Picture_Frame_Landscape_Damage
			{
				armor=0;
				material=-1;
				name="glass_hitpoint";
				visual="glass";
				passThrough=0;
				explosionShielding=0.2;
				radius=0.34999999;
			};
		};
		class Damage
		{
			tex[]=
			{
				"3den_objects\objects_f\picture_frame_f\glass_ca.paa",
				"3den_objects\objects_f\picture_frame_f\glass_damage_ca.paa",
				"3den_objects\objects_f\picture_frame_f\glass_damage_ca.paa"
			};
			mat[]=
			{
				"3den_objects\objects_f\picture_frame_f\glass.rvmat",
				"3den_objects\objects_f\picture_frame_f\glass_damage.rvmat",
				"3den_objects\objects_f\picture_frame_f\glass_damage.rvmat"
			};
		};
	};
	class Picture_Frame_Portrait_Base_F: Static
	{
		class HitPoints
		{
			class Picture_Frame_Portrait_Damage;
		};
	};
	class Picture_Frame_Portrait_F: Picture_Frame_Portrait_Base_F
	{
		author="Kydoimos";
		editorPreview="3den_objects\data_f\editor_previews_f\picture_frame_portrait_f.jpg";
		editorCategory="EdCat_Signs";
		editorSubcategory="EdSubcat_Office";
		displayName="$STR_Picture_Frame_Portrait_F";
		icon="iconObject_5x1";
		scope=2;
		scopeCurator=2;
		_generalMacro="PictureFrame_portrait_F";
		model="\3den_objects\objects_f\picture_frame_portrait_f\picture_frame_Portrait.p3d";
		vehicleClass="signs";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsMaterials[]=
		{
			"\3den_objects\objects_f\picture_frame_portrait_f\picture.rvmat"
		};
		hiddenSelectionsTextures[]=
		{
			"\3den_objects\objects_f\picture_frame_portrait_f\picture_co.paa"
		};
		class HitPoints: HitPoints
		{
			class Picture_Frame_Portrait_Damage: Picture_Frame_Portrait_Damage
			{
				armor=0;
				material=-1;
				name="glass_hitpoint";
				visual="glass";
				passThrough=0;
				explosionShielding=0.2;
				radius=0.34999999;
			};
		};
		class Damage
		{
			tex[]=
			{
				"3den_objects\objects_f\picture_frame_f\glass_ca.paa",
				"3den_objects\objects_f\picture_frame_f\glass_damage_ca.paa",
				"3den_objects\objects_f\picture_frame_f\glass_damage_ca.paa"
			};
			mat[]=
			{
				"3den_objects\objects_f\picture_frame_f\glass.rvmat",
				"3den_objects\objects_f\picture_frame_f\glass_damage.rvmat",
				"3den_objects\objects_f\picture_frame_f\glass_damage.rvmat"
			};
		};
	};
	class Portable_GCS_Hub_F: Static
	{
		author="Kydoimos";
		editorPreview="3den_objects\data_f\editor_previews_f\portable_gcs_hub_f.jpg";
		dlc="3den_objects_mod";
		editorCategory="EdCat_Things";
		editorSubcategory="EdSubcat_Military";
		displayName="$STR_GCS_Hub_F";
		icon="iconObject_1x1";
		mapSize=2;
		scope=2;
		scopeCurator=2;
		_generalMacro="Portable_GCS_Hub_F";
		model="\3den_objects\objects_f\gcs_Hub_f\portable_GCS_Hub_f.p3d";
		vehicleClass="military";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsMaterials[]=
		{
			"\3den_objects\objects_f\gcs_f\gcs_02.rvmat"
		};
		hiddenSelectionsTextures[]=
		{
			"\3den_objects\objects_f\gcs_f\gcs_02_co.paa"
		};
	};
	class Portable_GCS_Hub_CTRG_F: Portable_GCS_Hub_F
	{
		editorPreview="3den_objects\data_f\editor_previews_f\portable_gcs_hub_ctrg_f.jpg";
		displayName="$STR_GCS_CTRG_Hub_F";
		dlc="3den_objects_mod";
		_generalMacro="Portable_GCS_Hub_CTRG_F";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsMaterials[]=
		{
			"\3den_objects\objects_f\gcs_f\gcs_02.rvmat"
		};
		hiddenSelectionsTextures[]=
		{
			"\3den_objects\objects_f\gcs_f\gcs_02_CTRG_co.paa"
		};
	};
	class Portable_GCS_Packed_F: Static
	{
		author="Kydoimos";
		editorPreview="3den_objects\data_f\editor_previews_f\portable_gcs_packed_f.jpg";
		dlc="3den_objects_mod";
		editorCategory="EdCat_Things";
		editorSubcategory="EdSubcat_Military";
		displayName="$STR_GCS_Packed_F";
		icon="iconObject_1x1";
		mapSize=2;
		scope=2;
		scopeCurator=2;
		_generalMacro="Portable_GCS_Packed_F";
		model="\3den_objects\objects_f\gcs_Packed_f\Portable_GCS_Packed_f.p3d";
		vehicleClass="military";
		hiddenSelections[]=
		{
			"Camo"
		};
		hiddenSelectionsMaterials[]=
		{
			"\3den_objects\objects_f\gcs_f\gcs_02.rvmat"
		};
		hiddenSelectionsTextures[]=
		{
			"\3den_objects\objects_f\gcs_f\gcs_02_co.paa"
		};
	};
	class Portable_GCS_CTRG_Packed_F: Portable_GCS_Packed_F
	{
		editorPreview="3den_objects\data_f\editor_previews_f\Portable_GCS_CTRG_Packed_F.jpg";
		displayName="$STR_GCS_CTRG_Packed_F";
		dlc="3den_objects_mod";
		_generalMacro="Portable_GCS_Packed_CTRG_F";
		hiddenSelectionsTextures[]=
		{
			"\3den_objects\objects_f\gcs_f\gcs_02_CTRG_co.paa"
		};
	};
	class Portable_GCS_F: Static
	{
		class HitPoints
		{
			class Screen_01_damage;
			class Screen_02_damage;
			class Screen_03_damage;
		};
	};
	class Portable_GCS_Base_F: Portable_GCS_F
	{
		author="Kydoimos";
		editorPreview="3den_objects\data_f\editor_previews_f\Portable_GCS_F.jpg";
		dlc="3den_objects_mod";
		editorCategory="EdCat_Things";
		editorSubcategory="EdSubcat_Military";
		displayName="$STR_GCS_F";
		icon="iconObject_1x1";
		mapSize=2;
		scope=2;
		scopeCurator=2;
		_generalMacro="Portable_GCS_F";
		model="\3den_objects\objects_f\gcs_f\portable_GCS_F.p3d";
		vehicleClass="military";
		hiddenSelections[]=
		{
			"Camo_01",
			"Camo_02",
			"screen_01",
			"screen_02",
			"screen_03"
		};
		hiddenSelectionsMaterials[]=
		{
			"\3den_objects\objects_f\gcs_f\gcs_02.rvmat",
			"\3den_objects\objects_f\gcs_f\gcs_01.rvmat",
			"\3den_objects\objects_f\gcs_f\gcs_01_screen.rvmat",
			"\3den_objects\objects_f\gcs_f\gcs_01_screen.rvmat",
			"\3den_objects\objects_f\gcs_f\gcs_01_screen.rvmat"
		};
		hiddenSelectionsTextures[]=
		{
			"\3den_objects\objects_f\gcs_f\gcs_02_co.paa",
			"\3den_objects\objects_f\gcs_f\gcs_01_co.paa",
			"\3den_objects\objects_f\gcs_f\gcs_01_screen_co.paa",
			"\3den_objects\objects_f\gcs_f\gcs_01_screen_co.paa",
			"\3den_objects\objects_f\gcs_f\gcs_01_screen_co.paa"
		};
		class EventHandlers
		{
			hitPart="_unit = (_this select 0) select 0; if ((_unit getHitPointDamage ""Screen_01_Damage"") >= 0) then {_unit setObjectTextureGlobal [2, ""\3den_objects\objects_f\gcs_f\gcs_01_screen_co.paa""]}; if ((_unit getHitPointDamage ""Screen_02_Damage"") >= 0) then {_unit setObjectTextureGlobal [3, ""\3den_objects\objects_f\gcs_f\gcs_01_screen_co.paa""]}; if ((_unit getHitPointDamage ""Screen_03_Damage"") >= 0) then {_unit setObjectTextureGlobal [4, ""\3den_objects\objects_f\gcs_f\gcs_01_screen_co.paa""]}";
		};
		class HitPoints: HitPoints
		{
			class Screen_01_damage: Screen_01_damage
			{
				armor=0.1;
				material=-1;
				name="Screen_01_damage";
				visual="Screen_01_damage";
				passThrough=0;
				explosionShielding=0.40000001;
				radius=0.25;
			};
			class Screen_02_damage: Screen_02_damage
			{
				armor=0.1;
				material=-1;
				name="Screen_02_damage";
				visual="Screen_02_damage";
				passThrough=0;
				explosionShielding=0.1;
				radius=0.25;
			};
			class Screen_03_damage: Screen_03_damage
			{
				armor=0.1;
				material=-1;
				name="Screen_03_damage";
				visual="Screen_03_damage";
				passThrough=0;
				explosionShielding=0.1;
				radius=0.25;
			};
		};
		class Damage
		{
			tex[]=
			{
				"3den_objects\objects_f\gcs_f\gcs_01_screen_transparent_ca.paa",
				"3den_objects\objects_f\gcs_f\gcs_01_screen_damage_01_co.paa",
				"3den_objects\objects_f\gcs_f\gcs_01_screen_damage_01_co.paa"
			};
			mat[]=
			{
				"3den_objects\objects_f\gcs_f\gcs_01_screen_transparent.rvmat",
				"3den_objects\objects_f\gcs_f\gcs_01_screen_damage_01.rvmat",
				"3den_objects\objects_f\gcs_f\gcs_01_screen_damage_01.rvmat"
			};
		};
	};
	class Portable_GCS_Base_CTRG_F: Portable_GCS_Base_F
	{
		editorPreview="3den_objects\data_f\editor_previews_f\portable_gcs_ctrg_f.jpg";
		displayName="$STR_GCS_CTRG_F";
		dlc="3den_objects_mod";
		_generalMacro="Portable_GCS_Base_CTRG_F";
		hiddenSelectionsTextures[]=
		{
			"\3den_objects\objects_f\gcs_f\gcs_02_CTRG_co.paa",
			"\3den_objects\objects_f\gcs_f\gcs_01_CTRG_co.paa",
			"\3den_objects\objects_f\gcs_f\gcs_01_screen_co.paa",
			"\3den_objects\objects_f\gcs_f\gcs_01_screen_co.paa",
			"\3den_objects\objects_f\gcs_f\gcs_01_screen_co.paa"
		};
	};
	class Sign_Hotel_F: Items_base_F
	{
		author="Kydoimos";
		editorPreview="3den_objects\data_f\editor_previews_f\sign_hotel_f.jpg";
		dlc="3den_objects_mod";
		editorCategory="EdCat_Signs";
		editorSubcategory="EdSubCat_Roadsigns";
		displayName="$STR_Sign_Hotel_F";
		icon="iconObject_1x4";
		mapSize=2;
		scope=2;
		scopeCurator=2;
		_generalMacro="Sign_Hotel_F";
		model="\3den_objects\objects_f\sign_hotel_f\sign_hotel_f.p3d";
		vehicleClass="signs";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsMaterials[]=
		{
			"\3den_objects\objects_f\sign_hotel_f\sign_hotel.rvmat"
		};
		hiddenSelectionsTextures[]=
		{
			"\3den_objects\objects_f\sign_hotel_f\sign_hotel_co.paa"
		};
	};
	class Tactical_Screen_Base_F: Static
	{
		class HitPoints
		{
			class Screen_01_damage;
		};
	};
	class Tactical_Screen_F: Tactical_Screen_Base_F
	{
		author="Kydoimos";
		editorPreview="3den_objects\data_f\editor_previews_f\tactical_screen_f.jpg";
		dlc="3den_objects_mod";
		editorCategory="EdCat_Things";
		editorSubcategory="EdSubcat_Military";
		displayName="$STR_Tactical_Screen_F";
		icon="iconObject_5x1";
		scope=2;
		scopeCurator=2;
		_generalMacro="Land_Tactical_Screen_F";
		model="\3den_objects\objects_f\tactical_screen_f\tactical_screen_f.p3d";
		vehicleClass="small_items";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsMaterials[]=
		{
			"\3den_objects\objects_f\tactical_screen_f\screen_texture.rvmat"
		};
		hiddenSelectionsTextures[]=
		{
			"\3den_objects\objects_f\tactical_screen_f\screen_texture_co.paa"
		};
		class EventHandlers
		{
			hitPart="_unit = (_this select 0) select 0; if ((_unit getHitPointDamage ""Screen_01_Damage"") >= 0) then {_unit setObjectTextureGlobal [0, ""\3den_objects\objects_f\tactical_screen_f\screen_texture_damage_co.paa""]; _unit setObjectMaterialGlobal [0, ""\3den_objects\objects_f\tactical_screen_f\screen_texture_damage.rvmat""]; _unit setDamage 1;}";
		};
		class HitPoints: HitPoints
		{
			class Screen_01_damage: Screen_01_damage
			{
				armor=0.1;
				material=-1;
				name="Screen_01_damage";
				visual="Screen";
				passThrough=0;
				explosionShielding=0.40000001;
				radius=0.5;
			};
		};
		class Damage
		{
			tex[]=
			{
				"3den_objects\objects_f\tactical_screen_f\tactical_screen_transparent_ca.paa",
				"3den_objects\objects_f\tactical_screen_f\tactical_screen_damage_co.paa",
				"3den_objects\objects_f\tactical_screen_f\tactical_screen_damage_co.paa"
			};
			mat[]=
			{
				"3den_objects\objects_f\tactical_screen_f\tactical_screen_transparent.rvmat",
				"3den_objects\objects_f\tactical_screen_f\tactical_screen_damage.rvmat",
				"3den_objects\objects_f\tactical_screen_f\tactical_screen_damage.rvmat"
			};
		};
	};
	class Tactical_Screen_On_F: Tactical_Screen_F
	{
		displayName="$STR_Tactical_Screen_On_F";
		dlc="3den_objects_mod";
		hiddenSelectionsMaterials[]=
		{
			"\3den_objects\objects_f\tactical_screen_f\screen_texture_active.rvmat"
		};
		hiddenSelectionsTextures[]=
		{
			"\3den_objects\objects_f\tactical_screen_f\screen_texture_active_co.paa"
		};
	};
};
class CfgWeapons
{
	class VestItem;
	class Vest_Camo_Base;
	class V_Press_AAN_F: Vest_Camo_Base
	{
		author="Kydoimos";
		_generalMacro="V_Press_AAN_F";
		scope=2;
		picture="\3den_Objects\Objects_F\Press_Vest_F\UI\icon_V_PressVest_AAN_CA.paa";
		displayName="$STR_V_Press_AAN_F";
		model="\A3\Characters_F_EPC\Civil\equip_press_vest_01.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\3den_Objects\Objects_F\Press_Vest_F\Data\equip_press_vest_aan_co.paa"
		};
		descriptionShort="$STR_A3_SP_AL_II";
		class ItemInfo: VestItem
		{
			uniformModel="\A3\Characters_F_EPC\Civil\equip_press_vest_01.p3d";
			containerClass="Supply40";
			mass=40;
			hiddenSelections[]=
			{
				"camo"
			};
			class HitpointsProtectionInfo
			{
				class Chest
				{
					hitpointName="HitChest";
					armor=12;
					passThrough=0.40000001;
				};
				class Diaphragm
				{
					hitpointName="HitDiaphragm";
					armor=12;
					passThrough=0.40000001;
				};
				class Abdomen
				{
					hitpointName="HitAbdomen";
					armor=12;
					passThrough=0.40000001;
				};
				class Pelvis
				{
					hitpointName="HitPelvis";
					armor=12;
					passThrough=0.40000001;
				};
				class Body
				{
					hitpointName="HitBody";
					passThrough=0.40000001;
				};
			};
		};
	};
};
